version: '2'

services:
  
  app:
    build: .
    image: ngs-route-generator:dev
    environment:
      - "NODE_ENV=development"
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
      - "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}"
      - "AWS_NGS_BUCKET=${AWS_NGS_BUCKET}"
    volumes:
      - .:/home/ngs-route-generator
      - /home/ngs-route-generator/node_modules
   

  testapp:
    image: ngs-route-generator:dev
    environment:
      - "NODE_ENV=test"
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
      - "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}"
      - "AWS_NGS_BUCKET=${AWS_NGS_BUCKET}"
    volumes:
      - .:/home/ngs-route-generator
      - /home/ngs-route-generator/node_modules
    command:
      - 'npm run mocha'

  
  
